on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy App
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare bootstrap files
        run: |
          touch plugins.json
          mkdir release

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Gradle Build
        run: GITHUB_TOKEN=${{ secrets.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
}} ./gradlew clean build bootstrapPlugins

      - name: Push to release branch
        run: |
          git clone https://github.com/EmptyCharacter/empty-fQuesting-release.git deploy
          cp -r ./release/. ./deploy
          cp plugins.json deploy
          cd deploy
          
          git config --global user.email "farin.k.joshua@gmail.com"
          git config --global user.name "EmptyCharacter"
          git add -A
          git commit -m 'Plugins auto release'
          git push https://EmptyCharacter:${{ secrets.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 }}@github.com/EmptyCharacter/empty-fQuesting-release.git master